const words = [
  "characteristically",
  "chlorofluorocarbon",
  "compartmentalising",
  "compartmentalizing",
  "conversationalists",
  "counterrevolutions",
  "disproportionately",
  "electrocardiograms",
  "electrocardiograph",
  "institutionalising",
  "institutionalizing",
  "interchangeability",
  "internationalising",
  "internationalizing",
  "interrelationships",
  "misinterpretations",
  "misrepresentations",
  "oversimplification",
  "telecommunications",
  "transubstantiation",
  "unconstitutionally",
];
export default words;